
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label5;
	private global::Gtk.Entry edOp1;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label6;
	private global::Gtk.Entry edOp2;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label label8;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.ComboBox cbOpr;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label7;
	private global::Gtk.Entry edResult;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Button btExit;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.Button btOperate;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Op1");
		this.hbox5.Add (this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.edOp1 = new global::Gtk.Entry ();
		this.edOp1.CanFocus = true;
		this.edOp1.Name = "edOp1";
		this.edOp1.IsEditable = true;
		this.edOp1.InvisibleChar = '•';
		this.hbox5.Add (this.edOp1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.edOp1]));
		w2.Position = 1;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Op2");
		this.hbox6.Add (this.label6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.edOp2 = new global::Gtk.Entry ();
		this.edOp2.CanFocus = true;
		this.edOp2.Name = "edOp2";
		this.edOp2.IsEditable = true;
		this.edOp2.InvisibleChar = '•';
		this.hbox6.Add (this.edOp2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.edOp2]));
		w5.Position = 1;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Operator");
		this.hbox9.Add (this.label8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label8]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox9.Add (this.alignment1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment1]));
		w8.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.cbOpr = global::Gtk.ComboBox.NewText ();
		this.cbOpr.AppendText (global::Mono.Unix.Catalog.GetString ("+"));
		this.cbOpr.AppendText (global::Mono.Unix.Catalog.GetString ("-"));
		this.cbOpr.AppendText (global::Mono.Unix.Catalog.GetString ("*"));
		this.cbOpr.AppendText (global::Mono.Unix.Catalog.GetString ("/"));
		this.cbOpr.AppendText ("");
		this.cbOpr.Name = "cbOpr";
		this.cbOpr.Active = 0;
		this.hbox9.Add (this.cbOpr);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.cbOpr]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add (this.hbox9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Result");
		this.hbox7.Add (this.label7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label7]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.edResult = new global::Gtk.Entry ();
		this.edResult.CanFocus = true;
		this.edResult.Name = "edResult";
		this.edResult.IsEditable = false;
		this.edResult.InvisibleChar = '•';
		this.hbox7.Add (this.edResult);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.edResult]));
		w12.Position = 1;
		this.vbox2.Add (this.hbox7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btExit = new global::Gtk.Button ();
		this.btExit.CanFocus = true;
		this.btExit.Name = "btExit";
		this.btExit.UseStock = true;
		this.btExit.UseUnderline = true;
		this.btExit.Label = "gtk-quit";
		this.hbox8.Add (this.btExit);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btExit]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox8.Add (this.alignment2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment2]));
		w15.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btOperate = new global::Gtk.Button ();
		this.btOperate.CanFocus = true;
		this.btOperate.Name = "btOperate";
		this.btOperate.UseUnderline = true;
		this.btOperate.Label = global::Mono.Unix.Catalog.GetString ("_Operate");
		this.hbox8.Add (this.btOperate);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btOperate]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox2.Add (this.hbox8);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
		w17.Position = 4;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 269;
		this.DefaultHeight = 161;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.edOp1.Changed += new global::System.EventHandler (this.OnOpChanged);
		this.edOp2.Changed += new global::System.EventHandler (this.OnOpChanged);
		this.btExit.Clicked += new global::System.EventHandler (this.OnQuit);
		this.btOperate.Clicked += new global::System.EventHandler (this.OnOperate);
	}
}
